### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ktun95** [dictybase-playground/dicty-editor-lexical#1]
- [x] Initialize vite app
- [x] Add configurations
- [x] Replicate initial editor 
- [x] Create save button
- [x] add mui
- [x] switch to mui icons
- [ ] replace lexical theme system with mui theme system
- [x] save JSON to local storage
- [x] use local forage 
- [ ] Change format options plugin to use material ui

**Comment by ktun95** [comment]
ToolbarPlugin

- [x] add Toolbar plugin
- [x] convert ToolbarPlugin.tsx to typescript
- [x] fix linting issues
- [x] Fix insert link button
- [x] fix formatting options

**Comment by ktun95** [comment]
RE: Listeners vs Commands

Lexical Commands are similar to browser events, but are fired in the context of the lexical editor. Out of the box, lexical defines a number of commands that are dispatched in response to corresponding browser events. The editor.registerCommand() is used to register listeners for these commands. 

Lexical Listeners allow us to register "handlers", but for editor specific operations, such as when lexical commits an update to the DOM.

**Comment by ktun95** [comment]
Additonal Controls

- [x] Font options
- [x] h3, h4
- [x] remove code formatting
- [x] alignment drop down menu
- [x] Font Size options (10-20)
- [ ] Text Color
- [ ] highlight color
- [ ] subscript (dropdown)
- [ ] superscript (dropdown)
- [ ] clear formatting (dropdown)
- [x] outdent
- [x] indent
- [ ] insert (horizontal rule, image, table, youtube)
- [ ] read only mode
- [ ] move save to bottom
- [x] remove tree view

**Comment by ktun95** [comment]
On Firefox, sometimes the page will cause the browser to stop responding for a few seconds. I first noticed this after using localForage, but I'm not sure it's related. This seems to not be an issue on chrome

**Comment by cybersiddhu** [comment]
The `tsconfig` or typescript configuration is incomplete. Please fix that.

**Comment by ktun95** [comment]
- [x] fix tsconfig

Image Insertion

- [x] clean up code for insert image
- [x] fix image resizing
- [x] fix image caption
- [x] add missing styling

**Comment by ktun95** [comment]
- [ ] fix null selection

**Comment by ktun95** [comment]
Implementing the image insertion involved bringing in a lot of code all at once, which entailed a lot of eslint error fixing and reorganizing code, both of which I'm still not entirely done with. I also need to replace the css files I copied in with material ui's makeStyles. 

- [x] reorganize ImageNode.tsx
- [x] reorganize ImagesPlugin.ts
- [ ] implement text color button
- [ ] implement text highlight button
- [x] implement block type dropdown
- [ ] fix remaining linting issues

**Comment by ktun95** [comment]
- [ ] refactor useModal hook

**Comment by ktun95** [comment]
- [x] break up toolbarv2 into version a, b, and c
- [x] use jotai for state management
